export default {
  question: [
    'answerRegexp',
    'answerType',
    'AQseqNum',
    'isAmongConjointQuestions',
    'id',
    'items',
    'maxLabel',
    'maxValue',
    'minLabel',
    'minValue',
    'moreThanOne',
    'name',
    'parameters',
    'randomisationBlockMaxNumber',
    'randomize',
    'required',
    'RQseqNum',
    'sum',
    'sumLabel',
    'text',
    'type',
    'logic',
  ],
  item: ['id', 'action', 'AQseqNum', 'IseqNum', 'parameters', 'text', 'type', 'value', 'redirect'],
};
