export default {
  question: {
    answerRegexp: null,
    answerType: null,
    AQseqNum: null,
    childrens: [],
    experiment_id: null,
    id: '',
    isAmong: 'single',
    isAmongConjointQuestions: 0,
    items: [],
    view: 'form',
    key: null,
    logic: null,
    maxLabel: null,
    maxValue: null,
    minLabel: null,
    minValue: null,
    moreThanOne: 0,
    name: '',
    parameters: null,
    parent: null,
    pureText: '',
    randomisationBlockMaxNumber: 0,
    randomize: 0,
    required: 1,
    RQseqNum: null,
    sum: null,
    sumLabel: null,
    text: '',
    type: '',
    valid: true,
    validated: true,
  },
  item: {
    id: null,
    AQseqNum: null,
    IseqNum: null,
    action: 'none',
    redirect: {},
    parameters: {},
    text: null,
    type: 'standard',
    value: null,
  },
  parameters: {
    delay: '',
  },
};
